### PR TITLE
Exposes a TCP port environment variable

### PR DESCRIPTION
**Pull request by avtar**
This change was suggested during [a conversation in #fluid-work](https://botbot.me/freenode/fluid-work/2015-10-20/?msg=52343197&page=2).

### CODE REVIEW

**Comment by avtar** [comment]
@waharnum, @gtirloni please review when you have a chance. 

I tested this using a VM. I couldn't test the Supervisor config so I haven't modified that template. Although we might not need it if we use k8s. The only reason we were using Supervisor was because we needed something to restart failed processes, k8s should perform health checks and restart containers.

**Comment by avtar** [comment]
@jobara If this gets merged you can use the ``FIRST_DISCOVERY_SERVER_TCP_PORT`` variable in your VM.

**Comment by waharnum** [comment]
@gtirloni as I mentioned to @avtar yesterday, Supervisor config in Docker shouldn't be an issue of concern because it doesn't currently work for Docker with this role in its current form - I've had to make a fork (https://github.com/waharnum/ansible-nodejs-1) to work out some of the issues that I haven't made a PR for yet.

**Comment by gtirloni** [comment]
Thanks!

**Pull request merged**
